// Query TypeMap
import '@sanity/client'

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Timeline = {
  _type: 'timeline'
  items?: Array<{
    title?: string
    milestones?: Array<
      {
        _key: string
      } & Milestone
    >
    _type: 'item'
    _key: string
  }>
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Milestone = {
  _type: 'milestone'
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  tags?: Array<string>
  duration?: Duration
}

export type Feature = {
  _type: 'feature'
  title?: string
  description?: string
  icon?: 'shield' | 'heart' | 'calendar' | 'paw' | 'star' | 'clock' | 'mapPin' | 'check'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type CtaButton = {
  _type: 'ctaButton'
  label?: string
  linkType?: 'internal' | 'external' | 'phone' | 'email'
  internalLink?: PageReference
  externalUrl?: string
  phoneNumber?: string
  email?: string
  style?: 'primary' | 'secondary'
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  authorName?: string
  authorPhoto?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  quote?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  petName?: string
  rating?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleFont?: 'sans' | 'serif' | 'mono' | 'kranky'
  slug?: Slug
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroOverlayOpacity?: number
  heroButtons?: Array<
    {
      _key: string
    } & CtaButton
  >
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  duration?: Duration
  client?: string
  site?: string
  tags?: Array<string>
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Timeline)
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  >
  ctaTitle?: string
  ctaSubtitle?: string
  ctaPhoneNumber?: string
  ctaButtons?: Array<
    {
      _key: string
    } & CtaButton
  >
  ctaBackgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Duration = {
  _type: 'duration'
  start?: string
  end?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleFont?: 'sans' | 'serif' | 'mono' | 'kranky'
  slug?: Slug
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroOverlayOpacity?: number
  heroButtons?: Array<
    {
      _key: string
    } & CtaButton
  >
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Timeline)
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  >
  ctaTitle?: string
  ctaSubtitle?: string
  ctaPhoneNumber?: string
  ctaButtons?: Array<
    {
      _key: string
    } & CtaButton
  >
  ctaBackgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type HomeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'home'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  menuItems?: ArrayOf<HomeReference | PageReference | ProjectReference>
  footer?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type TestimonialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'testimonial'
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  titleFont?: 'sans' | 'serif' | 'mono' | 'kranky'
  tagline?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroOverlayOpacity?: number
  heroButtons?: Array<
    {
      _key: string
    } & CtaButton
  >
  aboutTitle?: string
  aboutContent?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2' | 'h3'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  aboutImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  featuresTitle?: string
  features?: Array<
    {
      _key: string
    } & Feature
  >
  testimonialsTitle?: string
  testimonials?: Array<
    {
      _key: string
    } & TestimonialReference
  >
  ctaTitle?: string
  ctaSubtitle?: string
  ctaPhoneNumber?: string
  ctaButtons?: Array<
    {
      _key: string
    } & CtaButton
  >
  ctaBackgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Timeline
  | SanityImageAssetReference
  | Milestone
  | Feature
  | PageReference
  | CtaButton
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Duration
  | Slug
  | Page
  | HomeReference
  | ProjectReference
  | Settings
  | TestimonialReference
  | Home
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

type ArrayOf<T> = Array<
  T & {
    _key: string
  }
>

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "home"][0]{    _id,    _type,    // Hero Section    title,    titleFont,    tagline,    heroImage,    heroOverlayOpacity,    heroButtons[]{      _key,      label,      linkType,      internalLink->{        _type,        "slug": slug.current      },      externalUrl,      phoneNumber,      email,      style    },    // About Section    aboutTitle,    aboutContent,    aboutImage,    // Features Section    featuresTitle,    features[]{      _key,      title,      description,      icon    },    // Testimonials Section    testimonialsTitle,    testimonials[]->{      _id,      _type,      authorName,      authorPhoto,      quote,      petName,      rating    },    // CTA Section    ctaTitle,    ctaSubtitle,    ctaPhoneNumber,    ctaButtons[]{      _key,      label,      linkType,      internalLink->{        _type,        "slug": slug.current      },      externalUrl,      phoneNumber,      email,      style    },    ctaBackgroundImage,    // SEO    overview  }
export type HomePageQueryResult = {
  _id: string
  _type: 'home'
  title: string | null
  titleFont: 'kranky' | 'mono' | 'sans' | 'serif' | null
  tagline: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }> | null
  heroImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  heroOverlayOpacity: number | null
  heroButtons: Array<{
    _key: string
    label: string | null
    linkType: 'email' | 'external' | 'internal' | 'phone' | null
    internalLink: {
      _type: 'page'
      slug: string | null
    } | null
    externalUrl: string | null
    phoneNumber: string | null
    email: string | null
    style: 'primary' | 'secondary' | null
  }> | null
  aboutTitle: string | null
  aboutContent: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'h2' | 'h3' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  aboutImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  featuresTitle: string | null
  features: Array<{
    _key: string
    title: string | null
    description: string | null
    icon: 'calendar' | 'check' | 'clock' | 'heart' | 'mapPin' | 'paw' | 'shield' | 'star' | null
  }> | null
  testimonialsTitle: string | null
  testimonials: Array<{
    _id: string
    _type: 'testimonial'
    authorName: string | null
    authorPhoto: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    quote: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: null
      level?: number
      _type: 'block'
      _key: string
    }> | null
    petName: string | null
    rating: number | null
  }> | null
  ctaTitle: string | null
  ctaSubtitle: string | null
  ctaPhoneNumber: string | null
  ctaButtons: Array<{
    _key: string
    label: string | null
    linkType: 'email' | 'external' | 'internal' | 'phone' | null
    internalLink: {
      _type: 'page'
      slug: string | null
    } | null
    externalUrl: string | null
    phoneNumber: string | null
    email: string | null
    style: 'primary' | 'secondary' | null
  }> | null
  ctaBackgroundImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  overview: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial"] | order(_createdAt desc){    _id,    _type,    authorName,    authorPhoto,    quote,    petName,    rating  }
export type TestimonialsQueryResult = Array<{
  _id: string
  _type: 'testimonial'
  authorName: string | null
  authorPhoto: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  quote: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }> | null
  petName: string | null
  rating: number | null
}>

// Source: sanity/lib/queries.ts
// Variable: pagesBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    _type,    // Hero Section    title,    titleFont,    overview,    heroImage,    heroOverlayOpacity,    heroButtons[]{      _key,      label,      linkType,      internalLink->{        _type,        "slug": slug.current      },      externalUrl,      phoneNumber,      email,      style    },    // Page Content    body,    "slug": slug.current,    // CTA Section    ctaTitle,    ctaSubtitle,    ctaPhoneNumber,    ctaButtons[]{      _key,      label,      linkType,      internalLink->{        _type,        "slug": slug.current      },      externalUrl,      phoneNumber,      email,      style    },    ctaBackgroundImage  }
export type PagesBySlugQueryResult = {
  _id: string
  _type: 'page'
  title: string | null
  titleFont: 'kranky' | 'mono' | 'sans' | 'serif' | null
  overview: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }> | null
  heroImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  heroOverlayOpacity: number | null
  heroButtons: Array<{
    _key: string
    label: string | null
    linkType: 'email' | 'external' | 'internal' | 'phone' | null
    internalLink: {
      _type: 'page'
      slug: string | null
    } | null
    externalUrl: string | null
    phoneNumber: string | null
    email: string | null
    style: 'primary' | 'secondary' | null
  }> | null
  body: Array<
    | ({
        _key: string
      } & Timeline)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  > | null
  slug: string | null
  ctaTitle: string | null
  ctaSubtitle: string | null
  ctaPhoneNumber: string | null
  ctaButtons: Array<{
    _key: string
    label: string | null
    linkType: 'email' | 'external' | 'internal' | 'phone' | null
    internalLink: {
      _type: 'page'
      slug: string | null
    } | null
    externalUrl: string | null
    phoneNumber: string | null
    email: string | null
    style: 'primary' | 'secondary' | null
  }> | null
  ctaBackgroundImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    _type,    // Hero Section    title,    titleFont,    overview,    heroImage,    heroOverlayOpacity,    heroButtons[]{      _key,      label,      linkType,      internalLink->{        _type,        "slug": slug.current      },      externalUrl,      phoneNumber,      email,      style    },    // Project Details    coverImage,    duration,    client,    site,    tags,    "slug": slug.current,    // Project Content    description,    // CTA Section    ctaTitle,    ctaSubtitle,    ctaPhoneNumber,    ctaButtons[]{      _key,      label,      linkType,      internalLink->{        _type,        "slug": slug.current      },      externalUrl,      phoneNumber,      email,      style    },    ctaBackgroundImage  }
export type ProjectBySlugQueryResult = {
  _id: string
  _type: 'project'
  title: string | null
  titleFont: 'kranky' | 'mono' | 'sans' | 'serif' | null
  overview: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }> | null
  heroImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  heroOverlayOpacity: number | null
  heroButtons: Array<{
    _key: string
    label: string | null
    linkType: 'email' | 'external' | 'internal' | 'phone' | null
    internalLink: {
      _type: 'page'
      slug: string | null
    } | null
    externalUrl: string | null
    phoneNumber: string | null
    email: string | null
    style: 'primary' | 'secondary' | null
  }> | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  duration: Duration | null
  client: string | null
  site: string | null
  tags: Array<string> | null
  slug: string | null
  description: Array<
    | ({
        _key: string
      } & Timeline)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        alt?: string
        _type: 'image'
        _key: string
      }
  > | null
  ctaTitle: string | null
  ctaSubtitle: string | null
  ctaPhoneNumber: string | null
  ctaButtons: Array<{
    _key: string
    label: string | null
    linkType: 'email' | 'external' | 'internal' | 'phone' | null
    internalLink: {
      _type: 'page'
      slug: string | null
    } | null
    externalUrl: string | null
    phoneNumber: string | null
    email: string | null
    style: 'primary' | 'secondary' | null
  }> | null
  ctaBackgroundImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{    _id,    _type,    footer,    menuItems[]{      _key,      ...@->{        _type,        "slug": slug.current,        title      }    },    ogImage,  }
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  footer: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  menuItems: Array<
    | {
        _key: null
        _type: 'home'
        slug: null
        title: string | null
      }
    | {
        _key: null
        _type: 'page'
        slug: string | null
        title: string | null
      }
    | {
        _key: null
        _type: 'project'
        slug: string | null
        title: string | null
      }
  > | null
  ogImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: slugsByTypeQuery
// Query: *[_type == $type && defined(slug.current)]{"slug": slug.current}
export type SlugsByTypeQueryResult = Array<{
  slug: string | null
}>

declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "home"][0]{\n    _id,\n    _type,\n    // Hero Section\n    title,\n    titleFont,\n    tagline,\n    heroImage,\n    heroOverlayOpacity,\n    heroButtons[]{\n      _key,\n      label,\n      linkType,\n      internalLink->{\n        _type,\n        "slug": slug.current\n      },\n      externalUrl,\n      phoneNumber,\n      email,\n      style\n    },\n    // About Section\n    aboutTitle,\n    aboutContent,\n    aboutImage,\n    // Features Section\n    featuresTitle,\n    features[]{\n      _key,\n      title,\n      description,\n      icon\n    },\n    // Testimonials Section\n    testimonialsTitle,\n    testimonials[]->{\n      _id,\n      _type,\n      authorName,\n      authorPhoto,\n      quote,\n      petName,\n      rating\n    },\n    // CTA Section\n    ctaTitle,\n    ctaSubtitle,\n    ctaPhoneNumber,\n    ctaButtons[]{\n      _key,\n      label,\n      linkType,\n      internalLink->{\n        _type,\n        "slug": slug.current\n      },\n      externalUrl,\n      phoneNumber,\n      email,\n      style\n    },\n    ctaBackgroundImage,\n    // SEO\n    overview\n  }\n': HomePageQueryResult
    '\n  *[_type == "testimonial"] | order(_createdAt desc){\n    _id,\n    _type,\n    authorName,\n    authorPhoto,\n    quote,\n    petName,\n    rating\n  }\n': TestimonialsQueryResult
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    _type,\n    // Hero Section\n    title,\n    titleFont,\n    overview,\n    heroImage,\n    heroOverlayOpacity,\n    heroButtons[]{\n      _key,\n      label,\n      linkType,\n      internalLink->{\n        _type,\n        "slug": slug.current\n      },\n      externalUrl,\n      phoneNumber,\n      email,\n      style\n    },\n    // Page Content\n    body,\n    "slug": slug.current,\n    // CTA Section\n    ctaTitle,\n    ctaSubtitle,\n    ctaPhoneNumber,\n    ctaButtons[]{\n      _key,\n      label,\n      linkType,\n      internalLink->{\n        _type,\n        "slug": slug.current\n      },\n      externalUrl,\n      phoneNumber,\n      email,\n      style\n    },\n    ctaBackgroundImage\n  }\n': PagesBySlugQueryResult
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    _type,\n    // Hero Section\n    title,\n    titleFont,\n    overview,\n    heroImage,\n    heroOverlayOpacity,\n    heroButtons[]{\n      _key,\n      label,\n      linkType,\n      internalLink->{\n        _type,\n        "slug": slug.current\n      },\n      externalUrl,\n      phoneNumber,\n      email,\n      style\n    },\n    // Project Details\n    coverImage,\n    duration,\n    client,\n    site,\n    tags,\n    "slug": slug.current,\n    // Project Content\n    description,\n    // CTA Section\n    ctaTitle,\n    ctaSubtitle,\n    ctaPhoneNumber,\n    ctaButtons[]{\n      _key,\n      label,\n      linkType,\n      internalLink->{\n        _type,\n        "slug": slug.current\n      },\n      externalUrl,\n      phoneNumber,\n      email,\n      style\n    },\n    ctaBackgroundImage\n  }\n': ProjectBySlugQueryResult
    '\n  *[_type == "settings"][0]{\n    _id,\n    _type,\n    footer,\n    menuItems[]{\n      _key,\n      ...@->{\n        _type,\n        "slug": slug.current,\n        title\n      }\n    },\n    ogImage,\n  }\n': SettingsQueryResult
    '\n  *[_type == $type && defined(slug.current)]{"slug": slug.current}\n': SlugsByTypeQueryResult
  }
}
